// main.js - wires the WASM interpreter, the WebGPU bridge, and the page
// UI together. No bundler/build step: plain ES modules, served as static
// files (see README's "Running the frontend").

import { parseCsv } from './csv/parse.js';
import { createGpuBridge } from './gpu/bridge.js';
import { saveQuery } from './api/client.js';
// Build output of interp/ext/Makefile - not committed (see .gitignore),
// generated by `make` in interp/ext/ once Emscripten is installed.
import createInterpModule from './wasm/interp.js';

const GRAMMAR_PATH = '/resources/grammar-csv.txt';

let wasmModule = null;

const statusEl = document.getElementById('status');
const csvInput = document.getElementById('csv-file');
const queryInput = document.getElementById('query');
const runButton = document.getElementById('run');
const saveButton = document.getElementById('save');
const resultsEl = document.getElementById('results');

function setStatus(text) {
	statusEl.textContent = text;
}

async function init() {
	wasmModule = await createInterpModule();
	wasmModule.gpuBridge = createGpuBridge(wasmModule);

	const rc = wasmModule.ccall('wc_init', 'number', ['string'], [GRAMMAR_PATH]);
	if (rc !== 0) {
		throw new Error(`wc_init failed (code ${rc})`);
	}
}

function loadColumn(name, values) {
	const ptr = wasmModule._malloc(values.length * Float64Array.BYTES_PER_ELEMENT);
	try {
		wasmModule.HEAPF64.set(values, ptr >> 3);
		const rc = wasmModule.ccall(
			'wc_load_column_f64', 'number',
			['string', 'number', 'number'],
			[name, ptr, values.length],
		);
		if (rc !== 0) {
			throw new Error(`failed to load column "${name}" (code ${rc})`);
		}
	} finally {
		wasmModule._free(ptr);
	}
}

async function runQuery(source) {
	wasmModule.wcResults = [];
	// Asyncify makes wc_run awaitable transparently once it (transitively,
	// through gpu_sum) reaches an EM_ASYNC_JS import - {async: true} is
	// what makes cwrap return a Promise instead of blocking on it. See
	// interp/ext/builtins_gpu.c and interp/ext/Makefile's ASYNCIFY note.
	const run = wasmModule.cwrap('wc_run', 'number', ['string'], { async: true });
	const rc = await run(source);
	if (rc !== 0) {
		throw new Error(`query failed (code ${rc})`);
	}
	return wasmModule.wcResults;
}

csvInput.addEventListener('change', async () => {
	const file = csvInput.files[0];
	if (!file) {
		return;
	}
	const text = await file.text();
	const columns = parseCsv(text);
	const numeric = columns.filter((c) => c.type === 'f64');

	for (const col of numeric) {
		loadColumn(col.name, col.values);
	}

	const skipped = columns.length - numeric.length;
	setStatus(
		`Loaded ${numeric.length} numeric column(s) from ${file.name}` +
		(skipped ? ` (${skipped} non-numeric column(s) parsed but not loaded - see parse.js)` : '.'),
	);
});

runButton.addEventListener('click', async () => {
	setStatus('Running...');
	try {
		const results = await runQuery(queryInput.value);
		resultsEl.textContent = JSON.stringify(results, null, 2);
		setStatus('Done.');
	} catch (err) {
		setStatus(`Error: ${err.message}`);
	}
});

saveButton.addEventListener('click', async () => {
	const name = window.prompt('Save this query as:');
	if (!name) {
		return;
	}
	try {
		await saveQuery({ name, grammarPath: GRAMMAR_PATH, source: queryInput.value });
		setStatus(`Saved "${name}".`);
	} catch (err) {
		setStatus(`Save failed: ${err.message}`);
	}
});

init()
	.then(() => setStatus('Ready.'))
	.catch((err) => setStatus(`Init failed: ${err.message}`));
