// main.js - wires the WASM interpreter, the WebGPU bridge, and the page
// UI together. No bundler/build step: plain ES modules, served as static
// files (see README's "Running the frontend").

import { parseCsv } from './csv/parse.js';
import { createGpuBridge } from './gpu/bridge.js';
import { saveQuery, saveDashboard, listDashboards } from './api/client.js';
import { renderResults } from './charts/render.js';
import { createDashboard } from './dashboard.js';
// Build output of interp/ext/Makefile - not committed (see .gitignore),
// generated by `make` in interp/ext/ once Emscripten is installed.
import createInterpModule from './wasm/interp.js';

const GRAMMAR_PATH = '/resources/grammar-csv.txt';

let wasmModule = null;

const statusEl = document.getElementById('status');
const csvInput = document.getElementById('csv-file');
const queryInput = document.getElementById('query');
const runButton = document.getElementById('run');
const saveButton = document.getElementById('save');
const addToDashboardButton = document.getElementById('add-to-dashboard');
const resultsEl = document.getElementById('results');
const resultsJsonEl = document.getElementById('results-json');

function setStatus(text) {
	statusEl.textContent = text;
}

async function init() {
	// Without this, Module's preloaded-package loader resolves interp.data
	// (and, in some Emscripten versions, interp.wasm) against the *page's*
	// URL directory rather than this script's - fine when index.html and
	// wasm/ are siblings, wrong here since index.html is at web/ and the
	// build output is under web/src/wasm/. Confirmed by an actual browser
	// run 404ing on GET /interp.data (root) instead of /src/wasm/interp.data.
	wasmModule = await createInterpModule({
		locateFile: (path) => new URL(`./wasm/${path}`, import.meta.url).href,
	});
	wasmModule.gpuBridge = createGpuBridge(wasmModule);

	const rc = wasmModule.ccall('wc_init', 'number', ['string'], [GRAMMAR_PATH]);
	if (rc !== 0) {
		throw new Error(`wc_init failed (code ${rc})`);
	}
}

function loadF64Column(name, values) {
	const ptr = wasmModule._malloc(values.length * Float64Array.BYTES_PER_ELEMENT);
	try {
		wasmModule.HEAPF64.set(values, ptr >> 3);
		const rc = wasmModule.ccall(
			'wc_load_column_f64', 'number',
			['string', 'number', 'number'],
			[name, ptr, values.length],
		);
		if (rc !== 0) {
			throw new Error(`failed to load column "${name}" (code ${rc})`);
		}
	} finally {
		wasmModule._free(ptr);
	}
}

// '\x1f'-joined, matching wc_load_column_str_dict's expectation (see
// web_main.c and column.c's columnCreateStrDict). The joined string is
// allocated on the heap explicitly rather than passed as a ccall 'string'
// argument: ccall's automatic string marshaling allocates on Emscripten's
// *stack* (a fixed, small default - 64KB), which corrupts memory instead
// of erroring cleanly once a column's every-row-value string gets large.
// A 100k-row column reliably crashed with "memory access out of bounds"
// before this fix - see interp/ext/Makefile's EXPORTED_RUNTIME comment.
function loadStringColumn(name, values) {
	const joined = values.join('\x1f');
	const byteLen = wasmModule.lengthBytesUTF8(joined) + 1;
	const ptr = wasmModule._malloc(byteLen);
	try {
		wasmModule.stringToUTF8(joined, ptr, byteLen);
		const rc = wasmModule.ccall(
			'wc_load_column_str_dict', 'number',
			['string', 'number', 'number'],
			[name, ptr, values.length],
		);
		if (rc !== 0) {
			throw new Error(`failed to load column "${name}" (code ${rc})`);
		}
	} finally {
		wasmModule._free(ptr);
	}
}

async function runQuery(source) {
	wasmModule.wcResults = [];
	// Asyncify makes wc_run awaitable transparently once it (transitively,
	// through gpu_sum) reaches an EM_ASYNC_JS import - {async: true} is
	// what makes cwrap return a Promise instead of blocking on it. See
	// interp/ext/builtins_gpu.c and interp/ext/Makefile's ASYNCIFY note.
	const run = wasmModule.cwrap('wc_run', 'number', ['string'], { async: true });
	const rc = await run(source);
	if (rc !== 0) {
		throw new Error(`query failed (code ${rc})`);
	}
	return wasmModule.wcResults;
}

csvInput.addEventListener('change', async () => {
	const file = csvInput.files[0];
	if (!file) {
		return;
	}
	const text = await file.text();
	const columns = parseCsv(text);

	for (const col of columns) {
		if (col.type === 'f64') {
			loadF64Column(col.name, col.values);
		} else {
			loadStringColumn(col.name, col.values);
		}
	}

	const numeric = columns.filter((c) => c.type === 'f64').length;
	const categorical = columns.length - numeric;
	setStatus(`Loaded ${numeric} numeric and ${categorical} categorical column(s) from ${file.name}.`);
});

runButton.addEventListener('click', async () => {
	setStatus('Running...');
	try {
		const results = await runQuery(queryInput.value);
		renderResults(resultsEl, results);
		resultsJsonEl.textContent = JSON.stringify(results, null, 2);
		setStatus('Done.');
	} catch (err) {
		setStatus(`Error: ${err.message}`);
	}
});

saveButton.addEventListener('click', async () => {
	const name = window.prompt('Save this query as:');
	if (!name) {
		return;
	}
	try {
		await saveQuery({ name, grammarPath: GRAMMAR_PATH, source: queryInput.value });
		setStatus(`Saved "${name}".`);
	} catch (err) {
		setStatus(`Save failed: ${err.message}`);
	}
});

createDashboard({
	tilesContainer: document.getElementById('dashboard-tiles'),
	addButton: addToDashboardButton,
	runAllButton: document.getElementById('dashboard-run-all'),
	saveButton: document.getElementById('dashboard-save'),
	loadSelect: document.getElementById('dashboard-load-select'),
	loadButton: document.getElementById('dashboard-load'),
	getCurrentQuery: () => queryInput.value,
	runQuery,
	saveDashboard,
	listDashboards,
	setStatus,
});

init()
	.then(() => setStatus('Ready.'))
	.catch((err) => setStatus(`Init failed: ${err.message}`));
